### PR TITLE
adding preview.png

### PR DESCRIPTION
**Pull request by beelee1**

### CODE REVIEW

**Comment by beelee1** [comment]
think I'm still doing this wrong. At any rate we'll figure it out. The process. The fix should be good.

I'll do the yaml update now as well.

**Comment by DanVanAtta** [comment]
Perhaps you need to 'add' the preview.png file, it is not committed it apperas - just the old image file deleted.

**Comment by beelee1** [comment]
thanks I"ll try again

**Comment by beelee1** [comment]
@DanVanAtta I know you're busy and this probably low priority, but been a few days so thought I'd ask if this will work or if I should start over.

I'd like to try and fix one missing image issue or preview.png a day but don't want to leave any unresolved.

Thanks

**Pull request merged**
